In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [3]:
import FallVelocity as fv
reload(fv)
import Backwater as bw
reload(bw)

<module 'Backwater' from 'Backwater.pyc'>

In [4]:
f = fv.FallVelocity()

In [28]:
f.grain_size = 0.1

In [5]:
f.run()

In [6]:
f.finalize()

In [53]:
import Backwater as bw
reload(bw)
b = bw.Backwater()

In [54]:
b.run()

In [55]:
b.finalize()

In [18]:
import AgDegNormal as adN
reload(adN)

<module 'AgDegNormal' from 'AgDegNormal.py'>

In [19]:
a = adN.AgDeg()

In [123]:
import GSD_calculator as gsd
reload(gsd)

<module 'GSD_calculator' from 'GSD_calculator.py'>

In [124]:
g = gsd.GSD_calculator()
g.run()

In [125]:
g._datapts

array([(0.00976438813668527, 0.0), (0.031, 0.02), (0.062, 0.032),
       (0.125, 0.1), (0.25, 0.42), (0.5, 0.8340000000000001), (1.0, 0.97),
       (2.0, 0.99), (4.0, 1.0)], 
      dtype=[('diameters', '<f8'), ('fractions', '<f8')])

In [131]:
grain_stats = g.characteristic_size([70,50,30])
grain_stats

[0.39951691807960471, 0.28583147875448067, 0.19277635317599259]

In [76]:
import RouseVanoni_Equilibrium as rv
reload(rv)

<module 'RouseVanoni_Equilibrium' from 'RouseVanoni_Equilibrium.pyc'>

In [77]:
r = rv.RouseVanoni_Equilibrium(b = 0.05,
                                    u_star = 0.2,
                                    settling_velocity = 0.03,
                                    save_output = False)

In [78]:
r.run()
r.finalize()

In [83]:
r.RV_profile[10,1]

0.30745820244404265

In [157]:
r.settling_velocity

0.03

In [255]:
import DeltaNorm as dbw
reload(dbw)

d = dbw.DeltaNorm()

d.run()
d.finalize()

In [253]:
d.eta[-1]

0.0

In [223]:
d.print_x[d.fields[0]]

array([     0.        ,    500.44616243,   1000.89232487,   1501.3384873 ,
         2001.78464973,   2502.23081217,   3002.6769746 ,   3503.12313703,
         4003.56929946,   4504.0154619 ,   5004.46162433,   5504.90778676,
         6005.3539492 ,   6505.80011163,   7006.24627406,   7506.6924365 ,
         8007.13859893,   8507.58476136,   9008.0309238 ,   9508.47708623,
        10008.92324866,  10015.        ])

In [226]:
d.data[:,0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [291]:
import DensityStratification as ds
reload(ds)

d = ds.DensityStratification()
d.run()

In [293]:
d.normalized_velocity_with_stratification

array([ 16.55018302,  22.92434539,  26.14876617,  28.15368077,
        29.57928806,  30.67386979,  31.55631845,  32.29208724,
        32.9208178 ,  33.46823572,  33.9519315 ,  34.3844358 ,
        34.7749739 ,  35.13052418,  35.45648648,  35.7571204 ,
        36.03584226,  36.29543173,  36.5381792 ,  36.76599316,
        36.98047965,  37.18300236,  37.37472846,  37.55666424,
        37.72968294,  37.894547  ,  38.0519257 ,  38.20240955,
        38.346522  ,  38.48472895,  38.61744681,  38.74504901,
        38.86787159,  38.98621783,  39.10036224,  39.21055386,
        39.31701912,  39.41996432,  39.51957766,  39.61603107,
        39.7094817 ,  39.80007323,  39.88793693,  39.9731925 ,
        40.05594882,  40.13630429,  40.21434711,  40.29015506,
        40.36379489,  40.43532092,  40.49431143])

In [326]:
import SteadyStateAg as ss
reload(ss)

s = ss.SteadyStateAg()
s.run()

In [325]:
s.finalize()

In [342]:
s.bankfull_channel_depth[0]

3.7671638456250012