In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [3]:
import FallVelocity as fv
reload(fv)
import Backwater as bw
reload(bw)

<module 'Backwater' from 'Backwater.pyc'>

In [4]:
f = fv.FallVelocity()

In [28]:
f.grain_size = 0.1

In [5]:
f.run()

In [6]:
f.finalize()

In [53]:
import Backwater as bw
reload(bw)
b = bw.Backwater()

In [54]:
b.run()

In [55]:
b.finalize()

In [18]:
import AgDegNormal as adN
reload(adN)

<module 'AgDegNormal' from 'AgDegNormal.py'>

In [19]:
a = adN.AgDeg()

In [123]:
import GSD_calculator as gsd
reload(gsd)

<module 'GSD_calculator' from 'GSD_calculator.py'>

In [124]:
g = gsd.GSD_calculator()
g.run()

In [125]:
g._datapts

array([(0.00976438813668527, 0.0), (0.031, 0.02), (0.062, 0.032),
       (0.125, 0.1), (0.25, 0.42), (0.5, 0.8340000000000001), (1.0, 0.97),
       (2.0, 0.99), (4.0, 1.0)], 
      dtype=[('diameters', '<f8'), ('fractions', '<f8')])

In [131]:
grain_stats = g.characteristic_size([70,50,30])
grain_stats

[0.39951691807960471, 0.28583147875448067, 0.19277635317599259]

In [76]:
import RouseVanoni_Equilibrium as rv
reload(rv)

<module 'RouseVanoni_Equilibrium' from 'RouseVanoni_Equilibrium.pyc'>

In [77]:
r = rv.RouseVanoni_Equilibrium(b = 0.05,
                                    u_star = 0.2,
                                    settling_velocity = 0.03,
                                    save_output = False)

In [78]:
r.run()
r.finalize()

In [83]:
r.RV_profile[10,1]

0.30745820244404265

In [157]:
r.settling_velocity

0.03

In [10]:
import DeltaNorm as dbw
reload(dbw)

d = dbw.DeltaNorm()

d.run()
d.finalize()

In [9]:
d.print_x

array([(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
       (500.44616243306723, 1129.2666661879098, 1724.1624115046213, 2232.923302222754, 2687.4802757890925, 3103.7499209037032, 3489.7233318730573),
       (1000.8923248661345, 2258.5333323758196, 3448.3248230092427, 4465.846604445508, 5374.960551578185, 6207.4998418074065, 6979.446663746115),
       (1501.3384872992017, 3387.79999856373, 5172.487234513865, 6698.7699066682635, 8062.440827367279, 9311.24976271111, 10469.169995619173),
       (2001.784649732269, 4517.066664751639, 6896.649646018485, 8931.693208891016, 10749.92110315637, 12414.999683614813, 13958.89332749223),
       (2502.230812165336, 5646.333330939548, 8620.812057523106, 11164.61651111377, 13437.401378945462, 15518.749604518514, 17448.616659365285),
       (3002.6769745984034, 6775.59999712746, 10344.97446902773, 13397.539813336527, 16124.881654734558, 18622.49952542222, 20938.339991238347),
       (3503.123137031471, 7904.866663315369, 12069.13688053235, 15630.46311555928, 18

In [223]:
d.print_x[d.fields[0]]

array([     0.        ,    500.44616243,   1000.89232487,   1501.3384873 ,
         2001.78464973,   2502.23081217,   3002.6769746 ,   3503.12313703,
         4003.56929946,   4504.0154619 ,   5004.46162433,   5504.90778676,
         6005.3539492 ,   6505.80011163,   7006.24627406,   7506.6924365 ,
         8007.13859893,   8507.58476136,   9008.0309238 ,   9508.47708623,
        10008.92324866,  10015.        ])

In [226]:
d.data[:,0]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [291]:
import DensityStratification as ds
reload(ds)

d = ds.DensityStratification()
d.run()

In [293]:
d.normalized_velocity_with_stratification

array([ 16.55018302,  22.92434539,  26.14876617,  28.15368077,
        29.57928806,  30.67386979,  31.55631845,  32.29208724,
        32.9208178 ,  33.46823572,  33.9519315 ,  34.3844358 ,
        34.7749739 ,  35.13052418,  35.45648648,  35.7571204 ,
        36.03584226,  36.29543173,  36.5381792 ,  36.76599316,
        36.98047965,  37.18300236,  37.37472846,  37.55666424,
        37.72968294,  37.894547  ,  38.0519257 ,  38.20240955,
        38.346522  ,  38.48472895,  38.61744681,  38.74504901,
        38.86787159,  38.98621783,  39.10036224,  39.21055386,
        39.31701912,  39.41996432,  39.51957766,  39.61603107,
        39.7094817 ,  39.80007323,  39.88793693,  39.9731925 ,
        40.05594882,  40.13630429,  40.21434711,  40.29015506,
        40.36379489,  40.43532092,  40.49431143])

In [326]:
import SteadyStateAg as ss
reload(ss)

s = ss.SteadyStateAg()
s.run()

In [325]:
s.finalize()

In [23]:
import AgDegNormalSub as ad
reload(ad)

a = ad.AgDegNormalSub(friction = 'Manning',
							 Qf = 70,
							 If = 0.03,
							 L = 10000,
							 dx = 100,
							 S = 0.008,
							 Gtf = 700000,
							 D = 30,
							 porosity = 0.35,
							 kc = 75,
							 phi = 1,
							 alpha_r = 8.1,
							 alpha_t = 8.,
							 tau_c = 0.047,
							 nt = 1.5,
							 Cz = 22,
							 alpha_u = 0.5,
							 dt = 0.01,
							 totalT = 120,
							 print_dt = 20,
							 g = 9.81,
							 rho_w = 1000,
							 rho_s = 2650,
							 subsidence = 5,
							 channel_width = 25,
							 depositional_width = 25*60,
							 washload_fraction = 1.5,
							 sinuosity = 1.5,
							 verbose = False,
							 save_output = False)
a.run()
a.finalize()

In [26]:
var = a.bed_elevation
var[0], var[-2]

(102.26911259423767, 0.23724567562372906)

In [107]:
import Acronym_D as acr
reload(acr)

a = acr.Acronym_D()
a.run()
a.finalize()

In [66]:
a.averages

array([ (34.0, 0.9959459023328753, 0.20904528549189427, 0.17161731998420054, 0.002408775290475485, [0.0, 52.42400244888638, 100.0])], 
      dtype=[('Q', '<f8'), ('H', '<f8'), ('ustar', '<f8'), ('Shields', '<f8'), ('q_bedload', '<f8'), ('percent_finer', '<f8', (3,))])

In [62]:
a.bedload_statistics

{'Dg': 15.733415362194647,
 'sigma': 0.49941207555762934,
 'sigma_g': 1.4136373620647387}

In [111]:
a.characteristic_size['bedload'][3]

27.661547759243085

In [113]:
a.surface_statistics['sigma_g']

1.4142135623730951

In [114]:
a.bedload_statistics['Dg']

15.733415362194647

In [118]:
a.averages['ustar'][0]

0.20904528549189427

In [91]:
mydict = dict(zip(list(a.averages.dtype.names)[:-1], a.averages))

In [92]:
mydict

{'Q': (34.0, 0.9959459023328753, 0.20904528549189427, 0.17161731998420054, 0.002408775290475485, [0.0, 52.42400244888638, 100.0])}

In [93]:
names = a.averages.dtype.names

In [99]:
flow_dict = [dict(zip(a.averages.dtype.names, record)) for record in a.averages][0]

In [100]:
flow_dict['percent_finer']

array([   0.        ,   52.42400245,  100.        ])

In [104]:
p_finer_dict = [dict(zip(list(a.percent_finer['diameter']), flow_dict['percent_finer']))]

In [105]:
p_finer_dict

[{8.0: 0.0, 16.0: 52.424002448886377, 32.0: 100.0}]

In [109]:
a.percent_finer['bedload'][1]

52.424002448886377

In [364]:
import DensityStratification as ds
reload(ds)

d = ds.DensityStratification()
d.run()
d.finalize()

In [369]:
d.conc_norm_init[-1]

0.0009073334043798784